spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_NEON_HOST}/neondb?user=${PROD_SPRING_NEON_DATASOURCE_USERNAME}&password=${PROD_SPRING_NEON_DATASOURCE_PASSWORD}&sslmode=require&channelBinding=require&currentSchema=${PROD_USER_NEON_SCHEMA_NAME}

  jpa:
    hibernate:
      ddl-auto: update
