spring:
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            client-name: Google
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/api/v1/login/oauth2/code/google
            scope:
              - email
              - profile
            provider: google_custom
            #url to login: "http://localhost:port/{context-path}/oauth2/authorization/google"
        provider:
          google_custom:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8081
  servlet:
    context-path: /api/${app.version}

security:
  jwt:
    secret-key:
    expiration: 3600000 # 1 hour in milliseconds
  api:
    key:
    header: X-API-KEY
  oauth2:
    authorized-redirect-url-frontend: http://localhost:3000/oauth2/redirect

service:
  users:
    url: http://localhost:${service.users.port}/api/${service.users.version}/users
    port: 8082
    version: v1

app:
  version: v1