spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000
    requested-heartbeat: 60

    # Publisher configuration (cho RabbitTemplate nếu cần)
    publisher-confirm-type: correlated
    publisher-returns: true

    template:
      mandatory: true
      reply-timeout: 60000
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.5
        max-interval: 10000

    # Consumer configuration (quan trọng cho consumer)
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5
        prefetch: 1
        acknowledge-mode: auto
        default-requeue-rejected: false

        # Retry configuration - CHỈ CẦN Ở CONSUMER
        retry:
          enabled: true
          initial-interval: 1000    # Retry sau 1 giây
          max-attempts: 3           # Retry tối đa 3 lần
          multiplier: 1.5           # Tăng dần thời gian retry
          max-interval: 10000       # Tối đa 10 giây giữa các retry

security:
  api:

    key: c761c9f0bb379612afbfd6ffeca90261db961bb93bce17728bc2a74430a66c0a
    header: X-API-KEY
  jwt:
    secret-key: e2bd3b3c7af3861cc4b5eeeeba79892a25739cc44a56eef4c38b92d9b5a39159
    expiration: 3600000 # 1 hour in milliseconds

server:
  port: 4005
