app:
  ticket:
    secret-key: test-secret-Km8N9pQ2rS5tU7wX0yZ3bC6dF8gH1jK4mN7pQ0rS3tU6
    qr-code-size: 300

spring:
  application:
    name: ticket-service

  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          serviceUrl:
            defaultZone: http://eureka:8761/eureka/

  profiles:
    active: dev



