spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    username: postgres
    password: 2707
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 4008

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

paypal:
  client-id: AZgVDnqEVFg0tr0ya9PyVBdpprnuVHHPSXVWP5T3lws_kw5gBeTnY21zElSfw-WhttcB78Gaa3Sm6JWS
  client-secret: EETQLur6Ow-G-7kh-7gq6gAqKR4NIheJV9lQr5Tia8Uqa4y_8Ce99zWu57bifjS6kbxRqlFevsSrEM-W
  base-url: https://api-m.sandbox.paypal.com
  return-url: http://localhost:4008/api/payment/paypal/success
  cancel-url: http://localhost:4008/api/payment/paypal/cancel