spring:
  application:
    name: order-service

  cloud:
    discovery:
      enabled: true

  profiles:
    active: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/ # Eureka Server URL

