spring:
  profiles:
    active: prod

decorator:
  datasource:
    p6spy:
      enable-logging: true

# Scalar Config
# Ref: https://guides.scalar.com/scalar/scalar-api-references/integrations/spring-boot
scalar:
  enabled: true

  #  https://registry.scalar.com/@scalar/apis/galaxy/latest?format=json
  url: https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.json
  path: /scalar
