name: auth-cd-flow

on:
  push:
    branches: ["main-deployment"]
    paths:
      - "services/auth-service/**"
      - ".github/workflows/auth-service-cd.yml"
      - "pom.xml"

jobs:
  build:
    uses: ./.github/workflows/reusable-service-cd.yml
    with:
      service_name: auth
      service_path: services/auth-service
      image_name: lcaohoanq/metro-auth
    secrets: inherit
