name: eureka-ci-flow

on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "main-deployment", "develop"]
    paths:
      - "services/eureka-service/**"
      - ".github/workflows/eureka-service-ci.yml"
      - "pom.xml"
#   push:
#     branches: ["main", "main-deployment"]
#     paths:
#       - "services/eureka-service/**"
#       - ".github/workflows/eureka-service-ci.yml"
#       - "pom.xml"

permissions:
  checks: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service_name: eureka
      service_path: services/eureka-service
      run_sonar: false
      publish_test_report: true
    secrets: inherit
