name: order-cd-flow

on:
  push:
    branches: ["main-deployment"]
    paths:
      - "services/order-service/**"
      - ".github/workflows/order-service-cd.yml"
      - "pom.xml"

jobs:
  build:
    uses: ./.github/workflows/reusable-service-cd.yml
    with:
      service_name: order
      service_path: services/order-service
      image_name: lcaohoanq/metro-order
    secrets: inherit
