name: station-cd-flow

on:
  workflow_dispatch:
  push:
    branches: ["main-deployment"]
    paths:
      - "services/station-service/**"
      - ".github/workflows/station-service-cd.yml"
      - "pom.xml"

permissions:
  contents: read
  security-events: write

jobs:
  build:
    uses: ./.github/workflows/reusable-service-cd.yml
    with:
      service_name: station
      service_path: services/station-service
      image_name: lcaohoanq/metro-station
    secrets: inherit
