name: user-cd-flow

on:
  workflow_dispatch:
  push:
    branches: ["main-deployment"]
    paths:
      - "services/user-service/**"
      - ".github/workflows/user-service-cd.yml"
      - "pom.xml"

jobs:
  build:
    uses: ./.github/workflows/reusable-service-cd.yml
    with:
      service_name: user
      service_path: services/user-service
      image_name: lcaohoanq/metro-user
    secrets: inherit
